language: c
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
  - ALCOTEST_SHOW_ERRORS=1
  - PINS="irmin.dev:. irmin-mem.dev:. irmin-pack.dev:. irmin-fs.dev:. irmin-http.dev:. irmin-git.dev:. irmin-graphql.dev:. irmin-mirage.dev:. irmin-mirage-git.dev:. irmin-mirage-graphql.dev:. irmin-unix.dev:. irmin-test.dev:. irmin-chunk.dev:."
  - DISTRO=debian-stable
  matrix:
  - OCAML_VERSION=4.09 PACKAGE="irmin"
  - OCAML_VERSION=4.09 PACKAGE="ppx_irmin"
  - OCAML_VERSION=4.08 PACKAGE="irmin"
  - OCAML_VERSION=4.07 PACKAGE="irmin"
  - OCAML_VERSION=4.08 PACKAGE="irmin-fs"
  - OCAML_VERSION=4.07 PACKAGE="irmin-mem"
  - OCAML_VERSION=4.07 PACKAGE="irmin-git"
  - OCAML_VERSION=4.07 PACKAGE="irmin-http"
  - OCAML_VERSION=4.07 PACKAGE="irmin-chunk"
  - OCAML_VERSION=4.08 PACKAGE="irmin-mirage"
  - OCAML_VERSION=4.07 PACKAGE="irmin-mirage-git"
  - OCAML_VERSION=4.07 PACKAGE="irmin-mirage-graphql"
  - OCAML_VERSION=4.07 PACKAGE="irmin-graphql"
  - OCAML_VERSION=4.07 PACKAGE="irmin-pack"
  - OCAML_VERSION=4.07 PACKAGE="irmin-unix" REVDEPS="irmin-indexeddb"
