language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
  - ALCOTEST_SHOW_ERRORS=1
  - REVDEPS="irmin-indexeddb"
  - PACKAGE=irmin
  - PINS="irmin-indexeddb:https://github.com/samoht/irmin-indexeddb.git"
  matrix:
  - OCAML_VERSION=4.03 TESTS=true
  - OCAML_VERSION=4.02 TESTS=true
  - OCAML_VERSION=4.02 DEPOPTS=cohttp TESTS=false
  - OCAML_VERSION=4.03 DEPOPTS=git TESTS=false
  - OCAML_VERSION=4.02 DEPOPTS="cohttp git" TESTS=false
  - OCAML_VERSION=4.03 DEPOPTS=mirage-git TESTS=false
