platform:
  - x86

environment:
  CYG_ROOT: "C:\\cygwin"
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  PINS: "irmin.1.0.0:. irmin-http.1.0.0:. irmin-git.1.0.0:. irmin-mirage.1.0.0:. irmin-unix.1.0.0:."
  PACKAGE: "irmin-unix"
  TESTS: "false"
  EXTRA_REMOTES: "https://github.com/mirage/mirage-dev.git"

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/appveyor-opam.sh
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P make -P unzip -P git -P perl -P mingw64-x86_64-gcc-core"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/appveyor-opam.sh'"
